apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  labels: 
    app: app-voting
spec: 
  replicas: 1
  selector:
    matchLables:
      name: result
      app: app-voting
  template:
    metadata:
      name: result
      labels:
        name: result
        app: app-voting
    spec: 
      containers:
      - name: result
        iamge: dockersamples/examplevotingapp_result
        ports:
        - containerPort: 80
          name: result
