apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  labels: 
    app: app-voting
spec: 
  replicas: 1
  selector:
    matchLables:
      name: vote
      app: app-voting
  template:
    metadata:
      name: vote
      labels:
        name: vote
        app: app-voting
    spec: 
      containers:
      - name: vote
        iamge: dockersamples/examplevotingapp_vote
        ports:
        - containerPort: 80
          name: vote
